[mysql]
DATABASE_URL = "mysql+pymysql://root:niju@localhost:3306/fedex"
host = "localhost"  # Replace with your database host
port = "3306"       # Default MySQL port
user = "root"
password = "niju"
database="fedex"
